[package]
name = "rUniversalDB"
version = "0.1.0"
authors = ["Pasindu Muthukuda <pasindumuth@gmail.com>"]
edition = "2018"
default-run = "transact"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
